In addition to obtain bias-corrected standard errors, bootstrapping is widely used for computing confidence intervals (CI). In this section, we will discuss different types of two-sided bootstrap confidence intervals. Assume the true value of parameter $\theta$ is $\theta_0$, and the probability of the confidence intervals containing the $\theta_0$ is $1-\alpha$. Let $\Phi(z)$ be the standard normal distribution, then the $z_\alpha$ represents the $\alpha$th quantile of the distribution such that $z_\alpha = \Phi^{-1}(\alpha)$. The distribution function of the estimator $\hat \theta$ is $H(\theta) = \text{Pr}(\hat\theta \leq\theta)$. The consistent estimator of this distribution obtained from $b = 1,..., B$ bootstrap replications $\theta_b^*$ is $\hat H(\theta) = \frac{\#\{b:\theta_B^* \leq \theta\}}{B}$.

## Bootstrap normal CI

If normality holds, then the common approximate $(1-\alpha) \times 100\%$ symmetric CI is $$[\hat \theta + z_{\frac{1}{2}}\hat{se}_N(\hat \theta), \hat \theta + z_{1-\frac{1}{2}}\hat{se}_N(\hat \theta)]$$, where $\hat \theta$ is the estimated parameter, and $\hat se_N (\hat \theta) = \sqrt{\hat \psi/n}$ is the estimator of the asymptotic standard deviation of $\hat \theta$. For bootstrap normal confidence interval, $\hat{se}_N$ is replaced with $\hat{se}_B$ [@leeden2008], the bootstrap estimator of the standard deviation of $\hat \theta$, $$[\hat \theta + z_{\frac{1}{2}}\hat{se}_B(\hat \theta), \hat \theta + z_{1-\frac{1}{2}}\hat{se}_B(\hat \theta)]$$.

## Hall's percentile/Percentile-t CI

$$[2\hat{\theta} - \hat{H}^{-1}(1-\frac{1}{2}\alpha); 2\hat{\theta} - \hat{H}^{-1}(\frac{1}{2}\alpha)]$$
$$[\hat \theta + \hat t_{\frac{1}{2}\alpha}\hat{se}_B(\hat \theta); \hat \theta + \hat t_{1-\frac{1}{2}\alpha}\hat{se}_B(\hat \theta)]$$


## Percentile CI

$$[\hat H^{-1}(\frac{1}{2}\alpha); \hat H^{-1}(1- \frac{1}{2}\alpha)]$$

## Studentized CI/bootstrap-t CI



### Bias-Corrected and Bias-Corrected and accelerated CI

$$[\hat H^{-1}(\Phi(z[\frac{1}{2}\alpha])); \hat H^{-1}(\Phi(z[1-\frac{1}{2}\alpha]))]$$
