In addition to obtaining bias-corrected standard errors, bootstrapping is widely used for computing confidence intervals (CIs). In this section, we discuss different types of two-sided bootstrap confidence intervals. Let $\theta$ be the parameter of interest; $\hat \theta$ be a sample estimator of $\theta$; and $\hat \theta^*$ be the bootstrap estimate of $\hat \theta$. Assume the target confidence level (i.e., probability of a random confidence interval containing the true value of $\theta$) is $1-\alpha$. Let $\Phi(z)$ be the cumulative density function of the standard normal distribution, then $z_\alpha$ represents the $\alpha$ quantile of the standard normal distribution such that $z_\alpha = \Phi^{-1}(\alpha)$. A confidence interval is defined by limits $\hat\theta_{\frac{1}{2}\alpha}$ and $\hat\theta_{1-\frac{1}{2}\alpha}$ such that $\text{Pr}(\hat\theta_{\frac{1}{2}\alpha}<\theta < \hat\theta_{1-\frac{1}{2}\alpha}) = \alpha$.
<!-- ML: do you mean the cumulative density function? YZ: yes-->
<!-- is the true value of parameter $\theta$ is $\theta_0$,  -->
<!--ML: we don't say qth quantile; we say (100q) percentile or just q quantile YZ: got it--> 
<!-- ML: 1 - \alpha is ideal but may not always happen, as many CIs have below nominal coverage. Could you just say that the target confidence level is 1 - alpha? YZ: sure.--> 
<!-- The consistent estimator of this distribution obtained from $b = 1,..., B$ bootstrap replications $\theta_b^*$ is $\hat H(\theta) = \frac{\#\{b:\theta_B^* \leq \theta\}}{B}$. -->

## Bootstrap Normal CI

If normality holds, then the common approximate $(1-\alpha) \times 100\%$ symmetric CI is $$[\hat \theta - z_{1-\frac{1}{2}\alpha}\hat{se}_N, \hat \theta + z_{1-\frac{1}{2}\alpha}\hat{se}_N],$$ where $\hat \theta$ is the estimated parameter, and $\hat se_N$ is the estimator of the asymptotic standard deviation of $\hat \theta$. For bootstrap normal confidence interval, $\hat{se}_N$ is replaced with $\hat{se}^*$ [@vanderleeden2008],<!-- ML: I think Winnie used a different notation for bootstrap SE --> the bootstrap estimator of the standard deviation of $\hat \theta$, so the bootstrap normal CI can be constructed as $$[\hat \theta - z_{1-\frac{1}{2}\alpha}\hat{se}^*, \hat \theta + z_{1-\frac{1}{2}\alpha}\hat{se}^*].$$

## Basic/Hall's Percentile
<!-- ML: the description can be clearer, I think. Should we mention that the interval adjusts for bias? YZ: does it look better now?-->
The basic CI, also called Hall's percentile CI, uses quantiles of the bootstrapped distribution instead of the normal distribution to obtain more accurate results when $\hat \theta$ does not follow a normal distribution [@hall1992; @vanderleeden2008; @davison1997]. For the bootstrap distribution of bias, $\hat \theta^* - \hat \theta$, $\frac{1}{2}\alpha$ and $1-\frac{1}{2}\alpha$ quantiles can be computed by $\hat q_{\frac{1}{2}\alpha} =  \hat \theta^*_{\frac{1}{2}\alpha} - \hat \theta$ and $\hat q_{1-\frac{1}{2}\alpha} = \hat \theta^*_{1-\frac{1}{2}\alpha} - \hat \theta$. Replacing the quantiles from the bootstrap distribution of bias, the basic CI is $$[2\hat{\theta} - \hat \theta^*_{1-\frac{1}{2}\alpha}, 2\hat{\theta} - \hat \theta^*_{\frac{1}{2}\alpha}].$$<!-- ML: Use comma instead of semicolon YZ: Sure.-->

## Studentized/Bootstrap-$t$ CI
<!-- ML: I think it's important to make clear what se_B^* is, and that it is specific to a particular bootstrap sample -->

Similar to the basic CI, bootstrap-$t$ CI replaces the quantiles of the normal distribution by quantiles of the bootstrap distribution. The difference between bootstrap-$t$ CI and the basic CI is that bootstrap-$t$ uses the bootstrap distribution of $t^* = (\hat \theta - \hat \theta ^*)/\hat{se}^*$ [@davison1997; @vanderleeden2008]. The bootstrap-$t$ confidence interval can be obtained by replacing $z_{1- \frac{1}{2}\alpha}$ by $t_{1-\frac{1}{2}\alpha}^*$, the $1-\frac{1}{2}\alpha$th quantiles of $t^*$,
$$[\hat \theta - t^*_{1-\frac{1}{2}\alpha}\hat{se}^*, \hat \theta + t^*_{1-\frac{1}{2}\alpha}\hat{se}^*],$$ where $\hat{se}$ is the bootstrap estimator of the asymptotic standard errors of $\hat \theta$. 

## Percentile CI

The percentile CI is formed by using quantiles directly from the bootstrapped distribution [@efron1982]. $$[\hat \theta_{\frac{1}{2}\alpha}^*; \hat \theta_{1-\frac{1}{2}\alpha}^*]$$ Although this percentile CI does not assume asymptotic normality of $\hat \theta$, it has been found to generate biased results [@efron1993].

## Bias-Corrected and Bias-Corrected and Accelerated CI

To correct the bias contained in the percentile CI, @efron1993 proposed the bias-corrected and accelerated (BCa) CI. They defined two quantiles, $\alpha_L$ and $\alpha_U$, as
$$
  \begin{aligned}
\alpha_L = \Phi\left(w + \frac{w + z_{\alpha/2}}{1- \alpha(w+z_{\alpha/2})}\right) \\
\alpha_U = \Phi\left(w + \frac{w + z_{1-\alpha/2}}{1- \alpha(w+z_{1-\alpha/2})}\right),
  \end{aligned}
$$
and suggested using these two quantiles to construct the BCa CI.
Here $w$ is the bias correction for the median, and $a$ is the acceleration (skewness) correction for the distribution of the estimator. These two correcting factors can be computed using the formulas below:
$$w = \Phi^{-1} \left(\frac{\sum_{r = 1}^{R} I_{\{\hat{\theta}^* < \theta\}}}{R+1}\right)$$
$$a = \frac{\sum_{j = 1}^{J}l_j^3}{6(\sum_{j = 1}^{J}l_j^2)^{\frac{3}{2}}}.$$
In the above equations, $I_{\{\hat{\theta}^* < \theta\}}$ is an indicator function, which equals 1 if $\hat\theta^* < \theta$ and 0 otherwise. In addition, $l_j^3$ represents an influence value for cluster $j$ and can be estimated by the grouped jackknife method that accounts for unequal group size [@vanderleeden2008; @lai2021].  
<!-- $$[\hat H^{-1}(\Phi(z[\frac{1}{2}\alpha])); \hat H^{-1}(\Phi(z[1-\frac{1}{2}\alpha]))]$$ -->
<!--ML: I did not italicize BCa. You can decide which one to use and I can make changes accordingly YZ: let's not italicize it-->